### ISSUE TITLE
loadProducts with subscription crash

### ISSUE THREAD

**Issue by thassman** [solar2d/com.solar2d-plugin.google.iap.billing.v2#4]
Hi,

When calling the loadProducts with a subscription product, and an empty table with in-app products it crashes with below java error:
It works fine in plugin.google.iap.billing but crashes in plugin.google.iap.billing.v2

```
store.loadProducts( {},listOfProducts, productCallback )



SM-A515F: Produc
Sep 09 21:33:39.111 tListRuntimeTask: dispatching Google IAP productList event
                    SM-A515F: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                    SM-A515F: 	at java.util.ArrayList.get(ArrayList.java:437)
                    SM-A515F: 	at plugin.google.iap.billi
Sep 09 21:33:39.111 ng.v2.BillingUtils.getOriginalJson(BillingUtils.java:93)
                    SM-A515F: 	at plugin.google.iap.billing.v2.BillingUtils.PushDetailsToLua(BillingUtils.java:143)
                    SM-A515F: 	at plugin.google.iap.billing.v2.ProductListRuntimeTask.executeUsing(ProductListRuntimeTask.java:57)
                    SM-A515F: 	at com.ansca.corona.CoronaRuntimeTaskDispatcher$TaskEvent.Send(CoronaRuntimeTaskDispatcher.java:179)
                    SM-A515F: 	
Sep 09 21:33:39.111 at com.ansca.corona.events.EventManager.sendEvents(EventManager.java:100)
                    SM-A515F: 	at com.ansca.corona.Controller.updateRuntimeState(Controller.java:325)
                    SM-A515F: 	at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame(CoronaGLSurfaceView.java:434)
                    SM-A515F: 	at com.ansca.corona.graphics.opengl.GLSurfa
Sep 09 21:33:39.111 ceView$GLThread.guardedRun(GLSurfaceView.java:1625)
                    SM-A515F: 	at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1380)
```

**Comment by scottrules44** [comment]
This should be fixed in new version, please rebuild to get new version.
Thanks for reporting!

**Comment by thassman** [comment]
I have tested it now, but still same issue.

confirmed in info.txt that release v9 is used of the plugin ```https://github.com/solar2d/com.solar2d-plugin.google.iap.billing.v2/releases/download/v9/2017.3105-android.tgz```

```
store.loadProducts( {},listOfProducts, productCallback )


ProductListRuntimeTask: dispatching Google 
Sep 11 15:35:24.298 IAP productList event
                    SM-A515F: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                    SM-A515F: 	at java.util.ArrayList.get(ArrayList.java:437)
                    SM-A515F: 	at plugin.google.iap.billing.v2.BillingUtils.getOriginalJson(BillingUtils.java:93)
                    SM-A515F: 	at plugin.google.iap.billing.v2.BillingUtils.PushDetailsToLua(
Sep 11 15:35:24.298 BillingUtils.java:142)
                    SM-A515F: 	at plugin.google.iap.billing.v2.ProductListRuntimeTask.executeUsing(ProductListRuntimeTask.java:57)
                    SM-A515F: 	at com.ansca.corona.CoronaRuntimeTaskDispatcher$TaskEvent.Send(CoronaRuntimeTaskDispatcher.java:179)
                    SM-A515F: 	at com.ansca.corona.events.EventManager.sendEvents(EventManager.java:100)
                    SM-A515F: 	at com.ansca.corona.Controller.updateRuntimeState(Controller.java:325)
                    SM-A515F: 	at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame(CoronaGLSurfaceView.java:434)
                    SM-A515F: 	at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThr
Sep 11 15:35:24.298 ead.guardedRun(GLSurfaceView.java:1625)
                    SM-A515F: 	at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1380)
```

**Comment by scottrules44** [comment]
@thassman sorry about that, can you try now

**Comment by thassman** [comment]
@scottrules44 I can confirm it works now, thanks a lot 👍🏻
